# Generated by Django 5.2.5 on 2025-12-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_room_number_tenant_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='patment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
