# Generated by Django 5.2.5 on 2026-01-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_patment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='patment_date',
            new_name='payment_date',
        ),
    ]
