# Generated by Django 5.2.5 on 2025-12-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
